### PR TITLE
chore: update feature runtime-benchmarks

### PR DESCRIPTION
**Pull request by neutrinoks**

### CODE REVIEW

**Review by Rqnsom — DISMISSED** [review]
What is the change here? 😃

**Comment by asmie** [comment]
> What is the change here? 😃

So, @Rqnsom , there was a minus inside the array of benchmarks, right before the `[pallet_move, MoveModule]` which made it unable to compile properly ;)

**Review by asmie — DISMISSED** [review]
Nice! :100:

**Comment by Rqnsom** [comment]
> So, @Rqnsom , there was a minus inside the array of benchmarks, right before the [pallet_move, MoveModule] which made it unable to compile properly ;)

Aha! That explains it! Thanks @asmie

**Review by Rqnsom — DISMISSED** [review]

**Review by Rqnsom — APPROVED** [review]

**Pull request merged**
